version: 2
updates:
  - package-ecosystem: github-actions
    assignees:
      - "mdelapenya"
    commit-message:
      prefix: "deps:"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    assignees:
      - "mdelapenya"
    commit-message:
      prefix: "deps:"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: monthly
  - package-ecosystem: docker
    assignees:
      - "mdelapenya"
    commit-message:
      prefix: "deps:"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: monthly
